name: Open Issue
on:
  workflow_dispatch:
    inputs:
      title:
        description: Issue title
        required: true
        type: string
      body:
        description: Issue body
        default: ""
        type: string
        #comment
jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lmishra20/open-issue-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.title }}
          body: ${{ inputs.body }}
